use std::{fs, path::PathBuf};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn strict_interface_is_the_sole_router_schema_authority() {
    let root = root();
    let source =
        fs::read_to_string(root.join("ethos/interface.ethos")).expect("strict Interface exists");
    let generated =
        fs::read_to_string(root.join("src/schema/lib/generated.rs")).expect("projection exists");
    let manifest = fs::read_to_string(root.join("src/bootstrap_manifest.rs"))
        .expect("authority manifest exists");

    assert!(source.starts_with("Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  ["));
    assert!(source.contains("RouterRequest.["));
    assert!(source.contains("RouterReply.["));
    assert!(
        !source.contains("HostName"),
        "dead vocabulary must be absent"
    );
    assert!(
        !root.join("schema").exists(),
        "legacy source tree must be absent"
    );
    assert!(generated.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface"
    ));
    assert!(!generated.contains("RouterRequest"));
    assert!(!generated.contains("RouterReply"));
    assert_eq!(manifest.matches("DeclarationSeat::new").count(), 190);
}

#[test]
fn crate_exports_the_exact_owned_interface_source() {
    assert_eq!(
        signal_router::ROUTER_INTERFACE_SOURCE,
        include_str!("../ethos/interface.ethos")
    );
    assert!(signal_router::ROUTER_INTERFACE_RUST.starts_with("// @generated"));
}
