// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VVbN ( z2VNMz ,) ;
pub struct z2VMR5 ( z2Vf1e ,) ;
pub struct z2VQHz ( z2VMfS ,) ;
pub struct z2VPfN {
    pub field_0: z2VdEo,
    pub field_1: z2VVd5,
    pub field_2: z2VQew,
    pub field_3: z2VbVV,
    pub field_4: z2Vaf5,
    pub field_5: z2Vd1b,
    pub field_6: z2VUTN,
}
pub struct z2VQGK(u64);
impl z2VQGK {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VXQX(std::string::String);
impl z2VXQX {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNRo ( z2VQC7 ,) ;
pub struct z2VX9R ( z2VNid ,) ;
pub struct z2VV5h(std::string::String);
impl z2VV5h {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VaLm ( z2VeFW ,) ;
pub struct z2VbKU(std::string::String);
impl z2VbKU {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VQNh {z2VbiE , z2VLVC , z2VaYK ,} 
pub struct z2VXG3 ( z2Vf1e ,) ;
pub struct z2VWUQ {
    pub field_0: Vec<z2VNh2>,
}
pub struct z2VNid {
    pub field_0: z2VVbN,
    pub field_1: z2VVYB,
    pub field_2: z2VYUB,
    pub field_3: Vec<std::string::String>,
    pub field_4: Vec<z2Vcrd>,
}
pub struct z2VbUg(std::string::String);
impl z2VbUg {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VRcj {
    pub field_0: z2VX9R,
    pub field_1: z2VL7S,
    pub field_2: z2VVui,
    pub field_3: z2VcpN,
    pub field_4: z2Vd2q,
}
pub enum z2VRts {z2VTCB , z2VMxJ , z2VcN3 ,} 
pub struct z2VfEY ( z2VLWZ ,) ;
pub struct z2VZVo {
    pub field_0: z2VQcL,
    pub field_1: z2VcsB,
}
pub struct z2VZNB ( z2VaJt ,) ;
pub struct z2VST8(u64);
impl z2VST8 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2Vdz8 ( z2VNwn ,) ;
pub struct z2VQGg {
    pub field_0: z2VXxh,
}
pub struct z2VYXM {
    pub field_0: Vec<u64>,
}
pub struct z2VY1V {
    pub field_0: z2VQcL,
    pub field_1: z2VcsB,
    pub field_2: z2VSRk,
}
pub struct z2VcTK ( z2VPn3 ,) ;
pub struct z2VW7S ( z2VeFW ,) ;
pub struct z2VPky(u64);
impl z2VPky {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VUhk(std::string::String);
impl z2VUhk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VURC ( z2VVNQ ,) ;
pub struct z2VbxJ(std::string::String);
impl z2VbxJ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VMfS {z2Ve98 , z2VPk5 , z2VYCc , z2VWbi , z2VcFF , z2Vd6L ,} 
pub struct z2VZU5 ( z2VLuJ ,) ;
pub struct z2VWsQ {
    pub field_0: z2VLTy,
    pub field_1: z2VZU5,
    pub field_2: z2VVAk,
    pub field_3: z2VZX5,
    pub field_4: z2Vd3E,
    pub field_5: z2Vd2q,
    pub field_6: z2VcpN,
    pub field_7: z2VSgE,
}
pub struct z2VZLC ( z2VQNh ,) ;
pub struct z2VSdJ ( z2VNRo ,) ;
pub struct z2VW7b {
    pub field_0: z2VfEY,
    pub field_1: z2VZLC,
}
pub struct z2VPaP {
    pub field_0: z2VURC,
}
pub struct z2VW1y(std::string::String);
impl z2VW1y {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VZMx {z2VMfh , z2VRvr ,} 
pub struct z2VQWj {
    pub field_0: z2VXxh,
}
pub struct z2Vcrd {
    pub field_0: z2VbKU,
    pub field_1: z2VV5h,
    pub field_2: z2VPAH,
    pub field_3: Vec<u64>,
}
pub struct z2Vafp ( z2VNwn ,) ;
pub struct z2VXxh(u64);
impl z2VXxh {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VLWZ {z2Vcer , z2VTUE , z2VNvN ,} 
pub struct z2Vd1b ( z2VLFW ,) ;
pub struct z2VcsM ( z2VPn3 ,) ;
pub struct z2VNK3 {
    pub field_0: z2VSqw,
    pub field_1: z2VZMx,
}
pub struct z2Vaf5(std::string::String);
impl z2Vaf5 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VdEo ( z2VNwn ,) ;
pub struct z2VcsB ( z2VUhk ,) ;
pub struct z2VLFW(std::string::String);
impl z2VLFW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNd2 {
    pub field_0: z2VQcL,
    pub field_1: z2VXxh,
}
pub struct z2VZfL {
    pub field_0: z2Ve3n,
    pub field_1: z2VbSs,
    pub field_2: z2Va6n,
    pub field_3: z2VMR5,
    pub field_4: z2VcsM,
    pub field_5: z2VXG3,
    pub field_6: z2VcTK,
    pub field_7: Option<z2VPn3>,
    pub field_8: z2VLx1,
    pub field_9: Option<z2VVPx>,
    pub field_10: z2Vafp,
    pub field_11: Option<z2VPn3>,
}
pub struct z2VcpN ( z2VLFW ,) ;
pub struct z2VWLp {
    pub field_0: z2VPs7,
    pub field_1: z2VaLm,
}
pub struct z2VPdn {
    pub field_0: z2VTFJ,
    pub field_1: Option<z2VNwn>,
}
pub enum z2VNh2 {z2VQBJ ( z2VPdn ,) , z2VUXc ( z2VPkk ,) , z2VRpm ( z2VPGB ,) , z2VdzM ( z2VWkj ,) ,} 
pub struct z2VbSs ( z2Vf1e ,) ;
pub enum z2VZGC {z2VdPV ( z2VZVo ,) , z2Vdxj ( z2VNid ,) , z2Vd1x ( z2VRcj ,) , z2VMyr ( z2VNj2 ,) , z2VQMp ( z2VUFf ,) , z2VMN6 ( z2VWLp ,) , z2Vd2e ( z2VNxf ,) , z2VWdr ( z2VTFJ ,) , z2VWzG ( z2VYdo ,) ,} 
pub struct z2VSqw ( z2VNMz ,) ;
pub struct z2VQcL ( z2VbUg ,) ;
pub struct z2VYdo {
    pub field_0: z2VQcL,
    pub field_1: z2VXxh,
}
pub struct z2Vf1e(u64);
impl z2Vf1e {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VZVN ( z2VNMz ,) ;
pub struct z2VVPx(std::string::String);
impl z2VVPx {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VLTy ( z2VNwn ,) ;
pub struct z2VPAH(u64);
impl z2VPAH {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VLuJ {z2VYLS , z2VYiG ,} 
pub struct z2VQew(std::string::String);
impl z2VQew {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNxf {
    pub field_0: Vec<u64>,
}
pub enum z2VaJt {z2VYWP , z2VXix , z2VNJF , z2VUHw , z2Vd77 ,} 
pub struct z2VbVV(std::string::String);
impl z2VbVV {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VVui ( z2VMPZ ,) ;
pub struct z2VUTN ( z2VQGK ,) ;
pub struct z2VNMz(std::string::String);
impl z2VNMz {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VTFJ {
    pub field_0: z2VQ8d,
    pub field_1: z2VVdV,
    pub field_2: Option<z2VLce>,
}
pub struct z2VMZv {
    pub field_0: z2VQcL,
    pub field_1: z2VXxh,
    pub field_2: z2VQHz,
}
pub struct z2VZXG ( z2VPfN ,) ;
pub enum z2VVNQ {z2Va7j , z2Vb6c , z2VXec , z2VY23 ,} 
pub struct z2VcvY(u64);
impl z2VcvY {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VQC7 {z2VP62 , z2VepV , z2VTee , z2VY2G , z2VLzK , z2VYnV , z2VXed , z2VZ7i , z2VXYJ ,} 
pub struct z2Ve3n ( z2VPn3 ,) ;
pub struct z2VPn3(std::string::String);
impl z2VPn3 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VYUB(std::string::String);
impl z2VYUB {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWkj {
    pub field_0: z2Vdz8,
    pub field_1: z2VbwY,
}
pub struct z2VbwY ( z2VVPx ,) ;
pub struct z2VSgE ( z2VQGK ,) ;
pub struct z2Va6n ( z2VPn3 ,) ;
pub enum z2VTf7 {z2VTZK , z2VTKg ,} 
pub struct z2VNKw ( z2VbxJ ,) ;
pub struct z2VUFf {
    pub field_0: z2VSH4,
}
pub enum z2VLx1 {z2VM4G ( z2Vf91 ,) ,} 
pub struct z2VT1o ( z2VNRo ,) ;
pub struct z2VeFW(std::string::String);
impl z2VeFW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VLce {
    pub field_0: z2VZNB,
    pub field_1: z2VXQX,
    pub field_2: Option<std::string::String>,
}
pub struct z2VVd5 ( z2VLuJ ,) ;
pub struct z2VSH4 ( z2VPfN ,) ;
pub struct z2VPkk {
    pub field_0: z2VVbN,
    pub field_1: z2VVYB,
}
pub enum z2VXoV {z2VYBQ ( z2VY1V ,) , z2VNok ( z2VMZv ,) , z2VPKn ( z2VNxf ,) , z2VLzz ( z2VSdJ ,) , z2VcmP ( z2VR5k ,) , z2VV3E ( z2Vbzo ,) , z2VPBN ( z2VT1o ,) , z2VcdN ( z2VNd2 ,) , z2Vc2V ( z2VQWj ,) , z2VNhW ( z2VPaP ,) , z2VeUs ( z2VNK3 ,) , z2VSmt ( z2VW7b ,) , z2VcTY ( z2VYXM ,) , z2VTty ( z2VLKE ,) , z2VTwc ( z2VQGg ,) ,} 
pub struct z2VVYB ( z2VNMz ,) ;
pub struct z2VNj2 {
    pub field_0: z2VQcL,
}
pub struct z2VVdV(u64);
impl z2VVdV {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VPGB {
    pub field_0: z2VZVN,
}
pub struct z2VL7S ( z2VWsQ ,) ;
pub struct z2VR5k {
    pub field_0: z2VQcL,
    pub field_1: z2VST8,
    pub field_2: z2VcvY,
    pub field_3: z2VPky,
    pub field_4: z2Vc6c,
}
pub struct z2Vf91(u64);
impl z2Vf91 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VNwn(std::string::String);
impl z2VNwn {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vc6c(u64);
impl z2Vc6c {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2Vd2q ( z2VQGK ,) ;
pub struct z2VQ8d ( z2VNMz ,) ;
pub struct z2Vbzo {
    pub field_0: z2VSqw,
    pub field_1: z2VTf7,
}
pub enum z2VMPZ {z2VUf6 , z2VRbU ,} 
pub struct z2VLKE {
    pub field_0: z2VNKw,
    pub field_1: z2VW7S,
    pub field_2: z2VZXG,
}
pub struct z2Vd3E(std::string::String);
impl z2Vd3E {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VZX5(std::string::String);
impl z2VZX5 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSRk ( z2VRts ,) ;
pub struct z2VVAk(std::string::String);
impl z2VVAk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VPs7 ( z2VbxJ ,) ;
