// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservationIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActorIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSlot(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OwnerIdentity {
    UnixUser(UnixUserIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EndpointKind {
    Human,
    HarnessSocket,
    PtySocket,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EndpointTransport {
    pub kind: EndpointKind,
    pub target: String,
    pub auxiliary: Option<String>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Actor {
    pub name: ActorIdentifier,
    pub process: Integer,
    pub endpoint: Option<EndpointTransport>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RegisterActor {
    pub actor: Actor,
    pub home: Option<RemoteRouterIdentity>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GrantDirectMessage {
    pub from: ActorIdentifier,
    pub to: ActorIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InstallStructuralChannels(ActorIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RouterBootstrapOperation {
    RegisterActor(RegisterActor),
    GrantDirectMessage(GrantDirectMessage),
    InstallStructuralChannels(InstallStructuralChannels),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterBootstrapDocument(Vec<RouterBootstrapOperation>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RouterObservationScope {
    Summary,
    MessageTrace,
    ChannelState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterSummaryQuery(EngineIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterMessageTraceQuery {
    pub engine: EngineIdentifier,
    pub message_slot: MessageSlot,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterChannelStateQuery {
    pub engine: EngineIdentifier,
    pub channel: ChannelIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterSummary {
    pub engine: EngineIdentifier,
    pub accepted_messages: Integer,
    pub routed_messages: Integer,
    pub deferred_messages: Integer,
    pub failed_messages: Integer,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RouterDeliveryStatus {
    Accepted,
    Routed,
    Delivered,
    Deferred,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterMessageTrace {
    pub engine: EngineIdentifier,
    pub message_slot: MessageSlot,
    pub status: RouterDeliveryStatus,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterMessageTraceMissing {
    pub engine: EngineIdentifier,
    pub message_slot: MessageSlot,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RouterChannelStatus {
    Installed,
    Missing,
    Disabled,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterChannelState {
    pub engine: EngineIdentifier,
    pub channel: ChannelIdentifier,
    pub status: RouterChannelStatus,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RouterObservationUnimplementedReason {
    NotInPrototypeScope,
    RouterStoreUnavailable,
    MessageTraceUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterObservationUnimplemented {
    pub scope: RouterObservationScope,
    pub reason: RouterObservationUnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterDaemonConfiguration {
    pub router_socket_path: WirePath,
    pub router_socket_mode: SocketMode,
    pub meta_router_socket_path: WirePath,
    pub meta_router_socket_mode: SocketMode,
    pub supervision_socket_path: WirePath,
    pub supervision_socket_mode: SocketMode,
    pub store_path: WirePath,
    pub bootstrap_path: Option<WirePath>,
    pub owner_identity: OwnerIdentity,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Summary(RouterSummaryQuery),
    MessageTrace(RouterMessageTraceQuery),
    ChannelState(RouterChannelStateQuery),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Summary(RouterSummary),
    MessageTrace(RouterMessageTrace),
    MessageTraceMissing(RouterMessageTraceMissing),
    ChannelState(RouterChannelState),
    Unimplemented(RouterObservationUnimplemented),
}

#[rustfmt::skip]
impl ObservationIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ObservationIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ObservationIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ObservationIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ObservationIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl ActorIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ActorIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ActorIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ActorIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ActorIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl EngineIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for EngineIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for EngineIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for EngineIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl ChannelIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ChannelIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ChannelIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ChannelIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ChannelIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl MessageSlot {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MessageSlot {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for MessageSlot {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl PartialEq<u64> for MessageSlot {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}
#[rustfmt::skip]
impl PartialOrd<u64> for MessageSlot {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for WirePath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for WirePath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for WirePath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for SocketMode {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl PartialEq<u64> for SocketMode {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}
#[rustfmt::skip]
impl PartialOrd<u64> for SocketMode {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for UnixUserIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for UnixUserIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl PartialEq<u64> for UnixUserIdentifier {
    fn eq(&self, other: &u64) -> bool {
        self.payload() == other
    }
}
#[rustfmt::skip]
impl PartialOrd<u64> for UnixUserIdentifier {
    fn partial_cmp(&self, other: &u64) -> Option<std::cmp::Ordering> {
        self.payload().partial_cmp(other)
    }
}

#[rustfmt::skip]
impl InstallStructuralChannels {
    pub fn new(payload: ActorIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ActorIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> ActorIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<ActorIdentifier> for InstallStructuralChannels {
    fn from(payload: ActorIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RouterBootstrapDocument {
    pub fn new(payload: Vec<RouterBootstrapOperation>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RouterBootstrapOperation> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RouterBootstrapOperation> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RouterBootstrapOperation>> for RouterBootstrapDocument {
    fn from(payload: Vec<RouterBootstrapOperation>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RouterSummaryQuery {
    pub fn new(payload: EngineIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> EngineIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineIdentifier> for RouterSummaryQuery {
    fn from(payload: EngineIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl OwnerIdentity {
    pub fn unix_user(payload: Integer) -> Self {
        Self::UnixUser(UnixUserIdentifier::new(payload))
    }
}

#[rustfmt::skip]
impl RouterBootstrapOperation {
    pub fn register_actor(payload: RegisterActor) -> Self {
        Self::RegisterActor(payload)
    }
    pub fn grant_direct_message(payload: GrantDirectMessage) -> Self {
        Self::GrantDirectMessage(payload)
    }
    pub fn install_structural_channels(payload: ActorIdentifier) -> Self {
        Self::InstallStructuralChannels(InstallStructuralChannels::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn summary(payload: EngineIdentifier) -> Self {
        Self::Summary(RouterSummaryQuery::new(payload))
    }
    pub fn message_trace(payload: RouterMessageTraceQuery) -> Self {
        Self::MessageTrace(payload)
    }
    pub fn channel_state(payload: RouterChannelStateQuery) -> Self {
        Self::ChannelState(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn summary(payload: RouterSummary) -> Self {
        Self::Summary(payload)
    }
    pub fn message_trace(payload: RouterMessageTrace) -> Self {
        Self::MessageTrace(payload)
    }
    pub fn message_trace_missing(payload: RouterMessageTraceMissing) -> Self {
        Self::MessageTraceMissing(payload)
    }
    pub fn channel_state(payload: RouterChannelState) -> Self {
        Self::ChannelState(payload)
    }
    pub fn unimplemented(payload: RouterObservationUnimplemented) -> Self {
        Self::Unimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for OwnerIdentity {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::UnixUser(payload)
    }
}

#[rustfmt::skip]
impl From<RegisterActor> for RouterBootstrapOperation {
    fn from(payload: RegisterActor) -> Self {
        Self::RegisterActor(payload)
    }
}

#[rustfmt::skip]
impl From<GrantDirectMessage> for RouterBootstrapOperation {
    fn from(payload: GrantDirectMessage) -> Self {
        Self::GrantDirectMessage(payload)
    }
}

#[rustfmt::skip]
impl From<InstallStructuralChannels> for RouterBootstrapOperation {
    fn from(payload: InstallStructuralChannels) -> Self {
        Self::InstallStructuralChannels(payload)
    }
}

#[rustfmt::skip]
impl From<RouterSummaryQuery> for Input {
    fn from(payload: RouterSummaryQuery) -> Self {
        Self::Summary(payload)
    }
}

#[rustfmt::skip]
impl From<RouterMessageTraceQuery> for Input {
    fn from(payload: RouterMessageTraceQuery) -> Self {
        Self::MessageTrace(payload)
    }
}

#[rustfmt::skip]
impl From<RouterChannelStateQuery> for Input {
    fn from(payload: RouterChannelStateQuery) -> Self {
        Self::ChannelState(payload)
    }
}

#[rustfmt::skip]
impl From<RouterSummary> for Output {
    fn from(payload: RouterSummary) -> Self {
        Self::Summary(payload)
    }
}

#[rustfmt::skip]
impl From<RouterMessageTrace> for Output {
    fn from(payload: RouterMessageTrace) -> Self {
        Self::MessageTrace(payload)
    }
}

#[rustfmt::skip]
impl From<RouterMessageTraceMissing> for Output {
    fn from(payload: RouterMessageTraceMissing) -> Self {
        Self::MessageTraceMissing(payload)
    }
}

#[rustfmt::skip]
impl From<RouterChannelState> for Output {
    fn from(payload: RouterChannelState) -> Self {
        Self::ChannelState(payload)
    }
}

#[rustfmt::skip]
impl From<RouterObservationUnimplemented> for Output {
    fn from(payload: RouterObservationUnimplemented) -> Self {
        Self::Unimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_SUMMARY: u64 = 0x0000000000000000;
    pub const INPUT_MESSAGE_TRACE: u64 = 0x0001000000000000;
    pub const INPUT_CHANNEL_STATE: u64 = 0x0002000000000000;
    pub const OUTPUT_SUMMARY: u64 = 0x0100000000000000;
    pub const OUTPUT_MESSAGE_TRACE: u64 = 0x0101000000000000;
    pub const OUTPUT_MESSAGE_TRACE_MISSING: u64 = 0x0102000000000000;
    pub const OUTPUT_CHANNEL_STATE: u64 = 0x0103000000000000;
    pub const OUTPUT_UNIMPLEMENTED: u64 = 0x0104000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Summary,
    MessageTrace,
    ChannelState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Summary,
    MessageTrace,
    MessageTraceMissing,
    ChannelState,
    Unimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Summary(_) => InputRoute::Summary,
            Self::MessageTrace(_) => InputRoute::MessageTrace,
            Self::ChannelState(_) => InputRoute::ChannelState,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Summary(_) => short_header::INPUT_SUMMARY,
            Self::MessageTrace(_) => short_header::INPUT_MESSAGE_TRACE,
            Self::ChannelState(_) => short_header::INPUT_CHANNEL_STATE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_SUMMARY => Ok(InputRoute::Summary),
            short_header::INPUT_MESSAGE_TRACE => Ok(InputRoute::MessageTrace),
            short_header::INPUT_CHANNEL_STATE => Ok(InputRoute::ChannelState),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Summary(_) => OutputRoute::Summary,
            Self::MessageTrace(_) => OutputRoute::MessageTrace,
            Self::MessageTraceMissing(_) => OutputRoute::MessageTraceMissing,
            Self::ChannelState(_) => OutputRoute::ChannelState,
            Self::Unimplemented(_) => OutputRoute::Unimplemented,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Summary(_) => short_header::OUTPUT_SUMMARY,
            Self::MessageTrace(_) => short_header::OUTPUT_MESSAGE_TRACE,
            Self::MessageTraceMissing(_) => short_header::OUTPUT_MESSAGE_TRACE_MISSING,
            Self::ChannelState(_) => short_header::OUTPUT_CHANNEL_STATE,
            Self::Unimplemented(_) => short_header::OUTPUT_UNIMPLEMENTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SUMMARY => Ok(OutputRoute::Summary),
            short_header::OUTPUT_MESSAGE_TRACE => Ok(OutputRoute::MessageTrace),
            short_header::OUTPUT_MESSAGE_TRACE_MISSING => {
                Ok(OutputRoute::MessageTraceMissing)
            }
            short_header::OUTPUT_CHANNEL_STATE => Ok(OutputRoute::ChannelState),
            short_header::OUTPUT_UNIMPLEMENTED => Ok(OutputRoute::Unimplemented),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Summary", "MessageTrace", "ChannelState"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
